/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package d_condicional_if;

public class App {
    public static void main(String[] args)
    {
        int media = 7;

        /** Operadores:
         > 
         >=
         <
         <=
         ==
         !=
         && e 
         | ou
         ! negacao
        **/

        if(media >=7){
            if(media == 10){     
                //APROVADO COM NOTA MAXIMA
            } else {
                //APROVADO
            }
        } else {
            //REPROVADO
        }
    }
}
