/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package c_variaveis_tipo_operadores;

public class App {
    public static void main(String[] args)
    {
        int idade = 0;
        float cotacao_dolar = 5.0f;
        double cotacao_euro = 5.0d;
        char genero = 'M';
        byte ponto = 0;
        boolean cadastrado = false;

        String nome = "Esse é um texto de uma variável String";
        // + // soma
        // - // subtracao
        // / // dibisao
        // * // multiplicacao
        // % //
    }
}

