/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package e_estrutura_escolha;

public class App {
    public static void main(String[] args)
    {
        int codigo_produto = 2;

        switch(codigo_produto){
        case 1:

            break;

        case 2:
            
            break;

        default:
        
        }
    }
}

 