/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package f_exercicio_quinze;

import java.util.Scanner;

public class App {
    public static void main(String[] args)
    {
        int numero;

        Scanner leitorScanner = new Scanner( System.in);

        System.out.print("Digite um valor: ");
        numero = leitorScanner.nextInt();
        leitorScanner.nextLine(); // Consumir a nova linha pendente

        if(numero >= 100 && numero <= 200){
            System.out.println("O número está no intervalo!");
        } else {
            System.out.println("O número não está no intervalo!");
        }
    }
}
